name: Node.js CI

on:
  push:
    branches: [ denys-test ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: prod

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: testing
      run: |
        npm i
        npm i -g appium
        BASEURL=https://amuse.com npm run iosBrowser
      env:
        BS_USER: denysfedotov_8lDg4I
        BS_KEY: dhgxwki9Qx4oQHeek7XD
        SLACK_WEBHOOK: ${{ secrets.DEMO_SLACK_APP_WEBHOOK }}
