# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron:  '0 5,11,17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    environment: prod

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: testing
      run: |
        npm i
        npm i -g appium
        BASEURL=https://amuse.com npm run iosBrowser
      env:
        BS_USER: ${{ secrets.BS_USER }}
        BS_KEY: ${{ secrets.BS_KEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        
